name: Pull Request Label Checker

on:
  workflow_call:
    inputs:
      version-configuration-path:
        required: false
        type: string
        default: .

jobs:
  label_checker:
    name: Version Increment Checker
    runs-on: windows-latest
    steps:
      - name: Checkout build-system repository
        uses: actions/checkout@v3
        with:
          repository: sergey-koryshev/build-system
          path: build-system-repo
      - name: Checkout target repository
        uses: actions/checkout@v3
      - name: Get increment information based on labels in PR
        shell: pwsh
        run: |
          $env:PSModulePath = $env:PSModulePath + ";$(Join-Path "${{ github.workspace }}" "build-system-repo" "scripts/ps")"
          Import-Module VersionHelper -Force -Verbose
          $splitRepositoryName = "${{ github.repository }}" -split "/"
          
          if ($splitRepositoryName.Length -ne 2) {
            throw "Repository name cannot be parsed: ${{ github.repository }}"
          }

          $incrementingPart = Get-IncrementingParts -PullRequestId ${{ github.event.pull_request.number }} -Owner $splitRepositoryName[0] -Repository $splitRepositoryName[1] -VersionConfigurationPath (Join-Path "${{ github.workspace }}" "${{ inputs.version-configuration-path }}") -AuthToken ${{ secrets.GITHUB_TOKEN }}
          Write-Host "Found incrementing parts: $($incrementingPart -join ', ')"